@id=3c4b9fcc-1521-42be-9e3e-397585ecb540
PUT http://localhost:5000/products/{{id}}
Content-Type: application/json

{
"name": "Mysz Razer",
"description": "Mysz Gamingowa Razer",
"Code": "AX12",
"Price": "299.0"
}